main: main.cpp Encode.h Encode.cpp treeNode.h List.h List.cpp Decode.h Decode.cpp reCreateTree.cpp reCreateTree.h GiveChar.cpp GiveChar.h ControlObject.cpp ControlObject.h
	dos2unix *
	g++ -std=c++11 -o Main *.cpp
